### ISSUE TITLE
Rename to Updated Dynamic Web Development with Seaside?

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/DynamicWebDevelopmentWithSeaside#1]
Question - should we re-title this project to Updated Dynamic Web Development with Seaside, to match with the naming convention of [UPBE](https://github.com/SquareBracketAssociates/UpdatedPharoByExample)? (To indicate that this is a re-formatting and updating project, and not the exact original source?)

**Comment by Ducasse** [comment]
No I would not put updated everywhere.

**Comment by SergeStinckwich** [comment]
Why not just reuse the existing repo here ?

**Comment by dmitrizagidulin** [comment]
Sounds good, not going to worry about adding 'updated' :)
